#!/usr/bin/env bash
# Push the cycle branch, open a PR, enable auto-merge, then poll until
# the PR lands on the base branch (or exit non-zero if it never does).
set -euo pipefail

: "${CYCLE_ID:?CYCLE_ID must be set}"
: "${CYCLE_TITLE:?CYCLE_TITLE must be set}"
: "${CYCLE_BASE:=main}"

branch=$(git rev-parse --abbrev-ref HEAD)
git push --set-upstream origin "${branch}"

pr_url=$(gh pr create --base "${CYCLE_BASE}" --title "cycle ${CYCLE_ID}: ${CYCLE_TITLE}" --body "Generated by cycle.")
pr_number=$(gh pr view "${branch}" --json number -q .number)

gh pr merge "${pr_number}" --squash --auto

# Poll until merged or timeout (30 minutes)
deadline=$(( $(date +%s) + 1800 ))
while [ "$(date +%s)" -lt "${deadline}" ]; do
  state=$(gh pr view "${pr_number}" --json state -q .state)
  if [ "${state}" = "MERGED" ]; then
    echo "${pr_url}"
    exit 0
  fi
  sleep 10
done

echo "pr.sh: PR did not merge within timeout" >&2
exit 1
