#!/usr/bin/env bash
# Push the cycle branch, open a PR, enable auto-merge, then poll until
# the PR lands on the base branch (or exit non-zero if it never does).
set -euo pipefail

: "${CYCLE_ID:?CYCLE_ID must be set}"
: "${CYCLE_TITLE:?CYCLE_TITLE must be set}"
: "${CYCLE_BASE:=main}"

branch=$(git rev-parse --abbrev-ref HEAD)
git push --set-upstream origin "${branch}"

pr_url=$(gh pr create --base "${CYCLE_BASE}" --title "cycle ${CYCLE_ID}: ${CYCLE_TITLE}" --body "Generated by cycle.")
pr_number=$(gh pr view "${branch}" --json number -q .number)

# First attempt: try GitHub auto-merge. Capture stderr without losing
# the exit code under set -e by short-circuiting the assignment with ||.
rc=0
err=$(gh pr merge "${pr_number}" --squash --auto 2>&1 1>/dev/null) || rc=$?

if [ "${rc}" -eq 0 ]; then
  # Auto-merge enabled. Poll until merged or timeout (30 minutes).
  deadline=$(( $(date +%s) + 1800 ))
  while [ "$(date +%s)" -lt "${deadline}" ]; do
    state=$(gh pr view "${pr_number}" --json state -q .state)
    if [ "${state}" = "MERGED" ]; then
      echo "${pr_url}"
      exit 0
    fi
    sleep 10
  done
  echo "pr.sh: PR did not merge within timeout" >&2
  exit 1
fi

# Auto-merge failed. If the failure is the "auto-merge disabled for this
# repo" signature, fall back to a synchronous squash merge. Any other
# failure propagates as-is.
case "${err}" in
  *enablePullRequestAutoMerge*|*"Auto merge is not allowed for this repository"*)
    fallback_rc=0
    gh pr merge "${pr_number}" --squash --delete-branch || fallback_rc=$?
    if [ "${fallback_rc}" -eq 0 ]; then
      # gh pr merge --delete-branch is a no-op on the synchronous merge path
      # (it only fires when GitHub schedules an async auto-merge). Delete the
      # remote ref explicitly so cycle/feature/* branches don't pile up.
      repo_slug=$(gh repo view --json nameWithOwner -q .nameWithOwner)
      delete_rc=0
      gh api -X DELETE "repos/${repo_slug}/git/refs/heads/${branch}" >/dev/null 2>&1 || delete_rc=$?
      if [ "${delete_rc}" -ne 0 ]; then
        echo "pr.sh: failed to delete remote branch ${branch} (exit ${delete_rc}); merge succeeded, continuing" >&2
      fi
      echo "${pr_url}"
      exit 0
    fi
    echo "pr.sh: auto-merge failed: ${err}" >&2
    echo "pr.sh: immediate-merge fallback also failed (exit ${fallback_rc})" >&2
    exit 1
    ;;
  *)
    echo "${err}" >&2
    exit "${rc}"
    ;;
esac
